# Generated by Django 5.0.1 on 2024-01-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'verbose_name': 'Cloth', 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AddField(
            model_name='cloth',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
