# Generated by Django 5.0.1 on 2024-01-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cloth_options_cloth_stock_size_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='sizes',
        ),
        migrations.AddField(
            model_name='cloth',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='xxl',
            field=models.IntegerField(default=0),
        ),
    ]
