# Generated by Django 5.0.1 on 2024-01-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cloth_sizes_cloth_l_cloth_m_cloth_s_cloth_xl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='l',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='m',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='s',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='xl',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='xxl',
        ),
        migrations.AddField(
            model_name='cloth',
            name='sizes',
            field=models.ManyToManyField(to='main.size'),
        ),
    ]
