# Generated by Django 5.0.1 on 2024-01-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_cloth_l_remove_cloth_m_remove_cloth_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='sizes',
        ),
        migrations.AddField(
            model_name='cloth',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloth',
            name='xxl',
            field=models.IntegerField(default=0),
        ),
    ]
