# Generated by Django 5.0.1 on 2024-02-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_accessory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
