# Generated by Django 5.0.1 on 2024-02-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1000)),
                ('code', models.CharField(max_length=100)),
                ('is_bought', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cloth',
            name='care_recommendations',
            field=models.TextField(default='none'),
        ),
    ]
