# Generated by Django 5.0.1 on 2024-02-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificate_alter_cloth_care_recommendations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
