# Generated by Django 5.0.1 on 2024-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField()),
                ('code', models.CharField(default='code', max_length=100)),
            ],
        ),
    ]
