# Generated by Django 5.0.1 on 2024-02-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_order_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='certificates',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
