# Generated by Django 5.0.1 on 2024-02-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_order_certificates_delete_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField()),
                ('code', models.CharField(default='code', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='certificates',
            field=models.ManyToManyField(to='main.certificate'),
        ),
    ]
