# Generated by Django 5.0.1 on 2024-02-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_order_name_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='certificate_nominal',
            new_name='certValue',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='middle_total',
            new_name='midValue',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='old_total',
            new_name='oldTotal',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='promo_percent',
            new_name='promoValue',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='delivery_method',
            new_name='deliveryMethod',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='delivery_type',
            new_name='deliveryType',
        ),
        migrations.AddField(
            model_name='cart',
            name='certificate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='certificate_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.certificate'),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.promo'),
        ),
    ]
