# Generated by Django 5.0.1 on 2024-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_certificate_nominal_cart_certvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='certificate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='promo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
