# Generated by Django 5.0.1 on 2024-02-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_cart_certificate_alter_cart_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='certificate_nominal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userorder',
            name='certificate_nominal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userorder',
            name='middle_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userorder',
            name='old_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userorder',
            name='promo_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='main.certificate'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='deliveryMethod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='deliveryType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
